### PR TITLE
Add basic support for border-image-source and border-image-slice.

### PR DESCRIPTION
**Pull request by xavidotron**
This adds basic support for border-image-source and border-image-slice.

This is sufficient for common uses of image borders in CSS.

It does not yet support non-default values for border-image-width, border-image-outset, or border-image-repeat, which I plan on addressing in future pull requests.

This is my first substantial contribution, so let me know if I should be putting this logic in a different place or otherwise approaching it differently. Thanks for your review!

First part of #2124.

### CODE REVIEW

**Comment by liZe** [comment]
That’s great, thanks a lot! The code seems to be almost perfect. ❤️

I’ll fix a couple of things and push small commits so that you can easily track what I’ve changed.

I think that we’ll merge this PR just after 42 is released (hopefully on Friday), because it already contains a lot of features and may cause a lot of bug reports.

**Comment by xavidotron** [comment]
Great, thanks for your review!

**Comment by liZe** [comment]
It looks like I’ve changed a lot of lines, but the modifications are actually minor. Thanks a lot, that’s a great pull request! 🙏🏽 

Here are the commits I’ve added:

- Rename tests and remove comments related to specification (you can ignore this commit, that’s a problem in my head).
- Simplify the SVG file used for tests (another pathological behavior).
- Separate [specified values](https://www.w3.org/TR/css-cascade/#specified-value) from [computed values](https://www.w3.org/TR/css-cascade/#computed). If you don’t know the difference between specified and computed values, this separation looks quite strange, but that’s important for many internal aspects of CSS. Blindly following what’s in the specification for this topic is always a good idea IMO, it avoids complex problems in the future. 😄
- Clean some code, mainly to use longer variable names and follow the famous (but unwritten) WeasyPrint code style. I’ve also used the default image sizing algorithm that can handle funny cases like images with no intrinsic size.
- Add CSS validation tests. We try to test specified values for complex cases, and generally rely on the rendering tests to check computed values. We’ll add more rendering tests when all the related properties are supported (I may have broken computed values for unsupported properties).

I also rebased the branch on top of "main", mainly to use and check the new linting rules.

If you want to support other properties, don’t hesitate to add new commits to this PR, we have some time before we merge it. There’s also the `border-image` shorthand to add into [`expanders.py`](https://github.com/Kozea/WeasyPrint/blob/main/weasyprint/css/validation/expanders.py).

**Comment by xavidotron** [comment]
I believe my existing change to `expanders.py` handles the `border-image` shorthand, though I may have missed something.

**Comment by xavidotron** [comment]
I believe this now supports all the border-image-* properties, including some basic test coverage.

**Comment by liZe** [comment]
> I believe my existing change to `expanders.py` handles the `border-image` shorthand, though I may have missed something.

I missed that!

> I believe this now supports all the border-image-* properties, including some basic test coverage.

Thank you! If everything is OK, it may even be ready for version 62.

**Comment by liZe** [comment]
Thanks a lot for this pull request.

All the relevant tests of the W3C testing suite pass. 🚀

We could add more drawing tests in WeasyPrint, but the code is already in very good shape and W3C tests give a good reason to be optimistic. Let’s merge if everything’s OK for you!

**Comment by xavidotron** [comment]
Sounds great! This works for my needs, so I'd be happy for it to be merged. Thanks for your work to improve this as well!

**Pull request merged**
