### PR TITLE
Handle target-*

### PR DESCRIPTION
**Pull request by liZe**
Replaces #572.

### CODE REVIEW

**Comment by liZe** [comment]
@Tontyna As said in #572, I've merged your PR in a branch and cleaned many things, including:
- more pythonic code and docstrings,
- don't use a global target collector,
- removed debugging info.

Looks like tests pass :smile:.

Thanks a lot for your work, that was really useful with good ideas and a clean global logic!

There's a lot of work to do before merging:
- Some functions get an optional `target_collector` because some boxes can't be anchors. I'm pretty sure that I've missed some parts of the code when it's needed (yes, we'll probably need to add this `target_collector` parameter in even more functions).
- The `target_collector`can probably be used in / instead of `_gather_links_and_bookmarks` (not sure about this, I have to check again but I'm really tired right now :wink:).
- We have to follow the specs more carefully about the `content` property, `attr()` and other CSS functions. The tricky part is to discard erratic functions sometimes during validation and sometimes during values computation. Moreover, there are subtle syntax changes in `attr()` and new values in `content`.
- And of course, we have to write some serious tests :wink:.

**Comment by Tontyna** [comment]
Do you want me to contribute to this branch? And if Yes: What shall I do?

----

You really wanna obey the DRAFT when it says that pre-computing `string-set` is forbidden? Why bother? What would be the point of delaying the evaluation? Just to make our hard life even harder? But then `bookmark-label` mustn't be pre-computed, too.
I assume the specs on `computed value` weren't updated when the properties evolved.

You know that currently -- consequence of 59a81dc -- a css like
```css
.test-string-set {
    string-set: teststring target-counter( attr(href) , somecounter);
}
```
crashes WeasyPrint?

**Comment by liZe** [comment]
> Do you want me to contribute to this branch? And if Yes: What shall I do?

Of course! You can do what you want in the previous listed points, the tests are probably the easiest point.

> You really wanna obey the DRAFT when it says that pre-computing string-set is forbidden? Why bother? What would be the point of delaying the evaluation? Just to make our hard life even harder?
> I assume the specs on computed value weren't updated when the properties evolved.

I'm really not sure about this last assertion.

Pre-calculating values when it's not specified is often a subtle trap I've met so many times. Computing values too early sometimes lead to embarrassing bugs like #137, and blindly following the spec (even a draft) now is often a better choice than finding bugs later and diving into old code to solve them.

I understand how frustrating and how useless it may appear, but it's better now than later.

> But then bookmark-label mustn't be pre-computed, too.

Indeed. Sharing some code to validate and compute `content-list` values is the way to go.

> You know that currently -- consequence of 59a81dc -- a css like […] crashes WeasyPrint?

That's why we need some tests :wink:.

**Comment by Tontyna** [comment]
Ok.

But please have a look at the `content()` function in `css/computed_values.py`. There is no *computation* done at all. No transformation, no calculation.  Replacing `attr()` with the attributes' value and verifying anchor names is just another step of *validation*. If it was possible to perform that step in `css/validation.py` we'd already done it there.
Makes the content-list suitable for `compute_content_list()` in `formatting_structure/build.py`, where the actual computation is done.

**Suggestion N°1:** Rename `content()` in css/computed_values to `content_list()`
At the moment WeasyPrint's implementation of the CSS property `content` is a free-style, half-baken interpretation, only handling its `<content-list>` part, sort of...

**Suggestion N°2:** The docstring for this `content_list()` function should be something along the lines of
```
"""
Prepare the <content-list> of content, bookmark-label and string-set properties.
Register targetted anchors in the target_collector.
"""
```

In any case: The targetted anchornames must be registered in the `target_collector` before the involved Box calls `compute_content_list()` for its string-set, bookmark-label, content.
IMHO `computed_values.compute()` is the perfect place to do that.

**Comment by liZe** [comment]
@Tontyna You're 100% right!

**Comment by Tontyna** [comment]
Wow, looks like you started spring cleaning...
Not shure how to contribute -- I mean: technically. I'm a git/GitHub newbie. Know how to branch this branch, but have no idea where to push / how to create a pull request to a branch other than master...

**Comment by liZe** [comment]
> Wow, looks like you started spring cleaning...

Oh yes I did!

> Not shure how to contribute -- I mean: technically. I'm a git/GitHub newbie. Know how to branch this branch, but have no idea where to push / how to create a pull request to a branch other than master...

You can fork the project and push to your fork just as you did with the previous PR. Then create a PR against the `target-collector` (you can choose the branch when creating the PR).

My next job is to move the computing part from `build.py` into `computed_values.py`. Now that everything is much more cleaner, I'll probably add support of `calc` too (and fix #357). Tests are also a must-have. Are you interested in one of these parts?

**Comment by liZe** [comment]
I've just realized my explanations are probably not clear at all, and that you probably need to update your fork with the latest git commits of this `target-collector` branch. Here's [how to update your GitHub fork](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository#7244456), that'll hopefully be useful!

**Comment by liZe** [comment]
> My next job is to move the computing part from build.py into computed_values.py

I've already done half of the work, pushing in the next days.

**Comment by liZe** [comment]
@Tontyna I'm happy with the current state of this branch, I only miss tests of bad syntaxes for `target-*` functions (the good ones are tested). I'll merge it soon.

**Comment by Tontyna** [comment]
Sorry for being absent so long -- had holidays, a flu and then a pile of undone jobs...
The list of commit messages looks promising. Will explore the branch this weekend and give feedback.

**Comment by Tontyna** [comment]
> I only miss tests of bad syntaxes

I can imagine thousands of *bad syntaxes". But I'm not good at writing unit-tests. Actually I parsed a lot of rather ugly html snippets -- WeasyPrint bravely handled the valid rules and discarded the invalid ones and of course the not-yet-supported, too.

Think the only missing test for `content` would be a css to cover the spec's comma separated URI list and the text for speech, something like  `content: url(xxx), url(yyy), <content-list> / "alternate text"`. And a style containing `leader()`. Just to prove that WeasyPrint eats them up / as a starting point for future implementation...
And maybe a test for `string-set` setting multiple strings.

All in all: I consider this PR is ready to merge.

**Comment by liZe** [comment]
> All in all: I consider this PR is ready to merge.

Well, you're right, tests can come later.

Thanks a lot for this PR, that was a lot of fun!

**Comment by Tontyna** [comment]
That was the first step to solve #23.

Next step should be: Make the `page` and `pages` (and probably other) counters of the `@page` context available in the document context . That's tricky. The target_collector could be extended to monitor the requested counters... already have  a few ideas how to do that, #93 is on my mind, too. Will PR when something useful emerges.

**Comment by liZe** [comment]
> Next step should be: Make the page and pages (and probably other) counters of the @page context available in the document context . That's tricky.

Oh yeah.

**Pull request merged**
