### PR TITLE
Implement bookmark-state support

### PR DESCRIPTION
**Pull request by randomstuff**
Addresses #648

### CODE REVIEW

**Comment by randomstuff** [comment]
Tests are currently broken. I think this is because the bookmarks are now all opened by default (as per the `bookmark-state` spec). I'm looking at it.

**Comment by randomstuff** [comment]
I fixed the tests. The notable ugly hack is the `BookmarkSubtree` which tries to be API-compatible with the tuples which where used before.

**Comment by liZe** [comment]
Thanks a lot! The code is clean and readable, it's a really nice feature to have. :heart:

**Comment by liZe** [comment]
For the record: I've cleaned a couple of things (mainly removing the tuple workaround) in 2ce0309.

**Pull request merged**
