### PR TITLE
Bookmark label

### PR DESCRIPTION
**Pull request by Tontyna**
Incited by #1145 I started a research about how to implement bookmark-labels for the `:before` and `:after` pseudo-elements and stumbled upon page counters and target counters not being updated in bookmark-labels at all.

Of course, nobody ever will use page or target counters in her bookmark-labels...

### CODE REVIEW

**Comment by Tontyna** [comment]
To actually generate a bookmark-label the pseudo-element must not only have a `bookmark-level` and a `bookmark-label`, but also have `content`, e.g.:

```css
.heading:before {
  content: '';
  bookmark-level: 1;
  bookmark-label: 'A Heading';
}
```

**Comment by Tontyna** [comment]
@liZe Maybe there is a better way of removing the duplicates. Best thing would be not to create them at all in the first place, but I was unable to find that first place.

**Comment by Tontyna** [comment]
There is something else not feeling quite right:

```css
div{
  bookmark-level: 1;
  bookmark-label: 'the main div';
}
div:before {
 content: 'before ';
 display:block;
 bookmark-level: 1;
 bookmark-label: 'before the div';
}
```

The `:before`-box is a child of the div's main BlockBox. Thus *the main div* precedes the *before the div* in the PDF outline. Both bookmarks target the same location in the PDF, the top left corner of the `:before`-box.

**Comment by liZe** [comment]
> The `:before`-box is a child of the div's main BlockBox. Thus _the main div_ precedes the _before the div_ in the PDF outline. Both bookmarks target the same location in the PDF, the top left corner of the `:before`-box.

Having a pseudo-element called `:before` when it’s actually **inside** the box is the problem, and there’s nothing we can do about this :wink:.

**Comment by liZe** [comment]
> @liZe Maybe there is a better way of removing the duplicates. Best thing would be not to create them at all in the first place, but I was unable to find that first place.

We have the same problem to remove the top border of a block on the second page when it’s split. There’s a `remove_decoration` mechanism to change the computed value for the second part of the block (and even the first one to remove the bottom border, but we don’t care for bookmarks). But it doesn’t work for repeating table headers and footers.

I don’t know if it’s possible to do something like that for bookmarks. Otherwise, I can just merge this pull request, it’s already really good.

**Comment by Tontyna** [comment]
> Otherwise, I can just merge this pull request

Yes, please merge it (and close #1145)

**Pull request merged**
