### PR TITLE
Consolidate space after/before list markers

### LINKED ISSUE #608: No space after inside list markers
```
<ul style="list-style-position: inside"><li>foo
```

This produces "•foo". Per CSS Counter Styles and CSS Lists, it should be "• foo" (which matches what every browser does).

### PR DESCRIPTION
**Pull request by Tontyna**
Should fix #608

### CODE REVIEW

**Comment by Tontyna** [comment]
I used a 0.5em (in the boxes font size) margin because that was the "space" that WeasyPrint applied until now to the `outside` lists, and until now nobody was complaining.

Didn't check the spec, always wondered how the browsers decide on the various distances in their lists and always had to apply css fixes&forces to make them display the way I wanted them.

**Comment by gsnedders** [comment]
@Tontyna `outside`'s positioning is basically undefined and really inconsistent (and causes web compat bugs!) and the space suffix is white-space collapsed. `inside` at least is relatively consistent.

**Comment by Tontyna** [comment]
Ok. A space/blank char after an inlined **text** marker. What should separate an **image** aka `list_style_image` marker?

**Comment by gsnedders** [comment]
See https://drafts.csswg.org/css-lists-3/#content-property (ignore the "not ready for implementation" box; this bit is pretty accurate).

**Comment by liZe** [comment]
I'd also like to avoid modifying the `style` objects, as it's shared by different boxes and may be frozen in the future if I ever find a workaround for the few cases left.

(And I like the space too, but you already knew that :innocent:.)

**Comment by Tontyna** [comment]
OMG! Not even my browser implements that draft about `::marker`s. I confess: I have no desire at all to dive into that...

What i **can** offer instead of an 0.5em space and although the difference will almost be imperceptible: 
A blank char after those inline markers.

**Comment by Tontyna** [comment]
@liZe: So we stay with the 0.5em space? (Didnt spot your comment at once, was busy reading the draft :smile: ) 
And some day in the future somebody will implement the full *CSS Lists Module Level 3*

**Comment by liZe** [comment]
> So we stay with the 0.5em space?

No problem. I'd just love to modify `marker.margin_*` and let `marker_box.style['margin_*']` unchanged.

**Comment by Tontyna** [comment]
You mean: `marker.margin_*` for the `outside` markers and a space char after `inline` text marker and an additional anonymous TextBox with a space cah for `inline` image markers?

**Comment by liZe** [comment]
OK. As inside markers can't be modified in `markers.py`, let's forget what I said. I'll add a `style.copy` to avoid any possible problem with `style` modification, and this code will go away when List 3 is implemented.

**Pull request merged**
