### PR TITLE
Use platform.uname instead of os.uname

### PR DESCRIPTION
**Pull request by Tontyna**
`platform.uname()` should work on all platforms (cf. https://github.com/Kozea/WeasyPrint/issues/1023#issuecomment-573250759) and therefore `weasyprint --info`, too.

Decided to `import platform` locally to avoid unnecessary initialization when there is no `--info` argument.

It's just educated guessing that it reveals interesting facts on Windows -- I don't have no Windows computer anymore.

Have no idea how to write a unit test for `PrintInfo` action :flushed:

### CODE REVIEW

**Comment by liZe** [comment]
Hello!

I had actually changed this in the `clean` branch too, in 10a7863. I really should have merged it sooner… And there’s also a test in this commit, at least checking that it doesn’t crash as it used to do on Windows :smile:.

**Comment by Tontyna** [comment]
Ah so simple, just `_run('--info')`

**Comment by liZe** [comment]
I’ve merged the `clean` branch.

> It's just educated guessing that it reveals interesting facts on Windows -- I don't have no Windows computer anymore.

Oo

**Comment by Tontyna** [comment]
> Oo

I know, [Linux sucks](https://itvision.altervista.org/why.linux.is.not.ready.for.the.desktop.current.html), but [Windows is an abomination](https://itvision.altervista.org/why-windows-10-sucks.html).

**Comment by liZe** [comment]
> I know, [Linux sucks](https://itvision.altervista.org/why.linux.is.not.ready.for.the.desktop.current.html), but [Windows is an abomination](https://itvision.altervista.org/why-windows-10-sucks.html).

That was interesting reading!

**Pull request closed without merging**
