### PR TITLE
Digital signature support

### LINKED ISSUE #752: Digital signature
I'd like to ask for digital signatures to be supported in WeasyPrint.
See [wikipedia](https://en.wikipedia.org/wiki/Digital_signature) for definition.
Not to be confused with superimposing a scanned handwritten signature, a digital signature would allow anyone holding a public key to verify that the pdf has not been tampered with and was indeed produced by whoever.

My use case:
I work for a university and have used WeasyPrint to implement all of our certificates and transcripts.
The university wants to allow students to send out these documents themselves without the need to print them out and sign and stamp them.
The recipient could then upload the document to some page on our site where a simple verification routine would tell them if the document is untampered with and authentic.

I include these examples of implementations in php:
https://manuals.setasign.com/setapdf-signer-manual/the-main-class/#index-4-1
https://tcpdf.org/examples/example_052/
(relevant implementation: https://github.com/tecnickcom/TCPDF/blob/master/tcpdf.php#L13411 and https://github.com/tecnickcom/TCPDF/blob/master/tcpdf.php#L7564)
https://www.kryptokoder.com/signwithext.html

This document from Adobe explains how the PDF standard wants the signature to be structured: https://www.adobe.com/devnet-docs/acrobatetk/tools/DigSig/Acrobat_DigitalSignatures_in_PDF.pdf

I'm not sure if this feature request fits with the main goal of WeasyPrint, i.e. to be able to structure pdf's via html+css but a utility function providing this functionality would certainly make life easier and help avoiding having to add another huge library dependency.

Also if anyone knows of a simple command line utility providing PDF-standard compliant signatures I'd love to hear about it.

### PR DESCRIPTION
**Pull request by hejsan**
Added hooks to support Digital Signatures via https://github.com/hejsan/WeasySign and allowed for writing multiple trailers.
Upped version number
Closes #752

### CODE REVIEW

**Comment by hejsan** [comment]
I soon realized that adding the actual Digital Signature code into WeasyPrint would be out of scope and it would add too many requirements to the project that most users wouldn't need and too much responsibility upon the WeasyPrint developers.
I chose to make minimal changes to WeasyPrint by simply allowing a Duck Typed signer to be passed.

**Comment by liZe** [comment]
That’s cool, thanks a lot!

> I soon realized that adding the actual Digital Signature code into WeasyPrint would be out of scope and it would add too many requirements to the project that most users wouldn't need and too much responsibility upon the WeasyPrint developers.

:heart:

> Upped version number

I usually do this when a new version is released.

Here’s my review:
- Keep version 51.
- There are some [linting problems](https://travis-ci.org/github/Kozea/WeasyPrint/jobs/671696756) that are pretty easy to fix :wink:.
- I’d prefer a less specific API change. Instead of `signer`, you can pass a `finisher` function that’s responsible of calling `pdf.finish()`. Other libraries could use it to post-process PDF files if they want. The end of the `write_pdf_metadata` could then be:

```python
pdf.finish() if finisher is None else finisher(pdf)
```

Your finisher function would call `write_signature_placeholder`, `pdf.finish` and `write_signature`.

(Out of curiosity :smile:: what’s University of Iceland’s use case for WeasyPrint?)

**Comment by hejsan** [comment]
Hi
I had thought about making it less specific and I agree.
I'm a programmer at the Universities IT department. We develop the inner web called Ugla (Ugla=Owl as in Athena goddess of wisdoms' pet, Athena is in the universities logo). It's a portal for most of the Unis' services.

We've used WeasyPrint since before it was called WeasyPrint, can't recall the name now. It's used to generate all the student transcripts, confirmations, certificates, diplomas, diploma supplement etc. I actually started using the predecessor a long time ago working for the Icelandic University of the Arts and I brought it with me. Before they were using some terrible php thing that was impossible to maintain, basically printing on a canvas.
You've made a great job of making the library much snappier and more elegant. I'm very happy to give something back.

I'll get to the changes later today - is it possible to see exactly what linting problems I need to fix? I'm not used to this travis thing.
And thank you for the positive attitude :)

**Comment by liZe** [comment]
> I had thought about making it less specific and I agree.

Cool.

> I'm a programmer at the Universities IT department. We develop the inner web called Ugla (Ugla=Owl as in Athena goddess of wisdoms' pet, Athena is in the universities logo). It's a portal for most of the Unis' services.
> 
> We've used WeasyPrint since before it was called WeasyPrint, can't recall the name now. It's used to generate all the student transcripts, confirmations, certificates, diplomas, diploma supplement etc. I actually started using the predecessor a long time ago working for the Icelandic University of the Arts and I brought it with me. Before they were using some terrible php thing that was impossible to maintain, basically printing on a canvas.

It’s great to know that WeasyPrint’s useful for you and for the whole university!

> You've made a great job of making the library much snappier and more elegant. I'm very happy to give something back.

Thanks a lot.

> I'll get to the changes later today.
> And thank you for the positive attitude :)

And thank you for the kind words :smile:.

**Comment by liZe** [comment]
Perfect, thank you!

**Pull request merged**
