### PR TITLE
feat: build windows wheels

### PR DESCRIPTION
**Pull request by naveen521kk**
fixes https://github.com/Kozea/WeasyPrint/issues/1241
TODO:
- [x] the license file isn't included in the wheel
- [x] Set up Github Actions to Test them and Build them
- [x] Also, https://github.com/Kozea/WeasyPrint/issues/1241#issuecomment-789090182

If anyone wants to try I had already built a wheel. 
[WeasyPrint-53.0-py3-none-win_amd64.zip](https://github.com/Kozea/WeasyPrint/files/6070806/WeasyPrint-53.0-py3-none-win_amd64.zip)

### CODE REVIEW

**Comment by naveen521kk** [comment]
@liZe is there any smoke tests that can be run to test those wheels?

**Comment by naveen521kk** [comment]
Any chance for reviewing it?

**Comment by liZe** [comment]
> Any chance for reviewing it?

Hello @naveen521kk.

Thanks for your hard work on this pull request, we’re sorry we took so much time to answer.

It’s a bit complicated right now for us to review this pull request, because there’s a lot of things going on with version 53: new packaging, new dependencies, etc. Moreover, providing wheels with embedded libraries is a really important decision, because it’s almost mandatory to provide them forever. It adds code that we’ll have to maintain and to test, knowing that we don’t have Windows installed on our computers.

The ideal solution would include:
- no extra Python code,
- a whole automation of packaging,
- packaging tests for all supported platforms.

Of course, this dream is a lot of work (if it’s ever possible :wink:, that’s sometimes the problem with dreams). This PR is definitely a huge step in the right direction, and we’re very grateful for that, but both fixing the technical details and accepting the [little cute puppy](https://youtu.be/tzFWz5fiVKU?t=1h3m21s) will take some time 🐕.

**Comment by naveen521kk** [comment]
> It adds code that we’ll have to maintain and to test, knowing that we don’t have Windows installed on our computers.

You can always ping me, I should be able to help if things don't work :)
I have documented the code I wrote so that it doesn't create problems and is easy for anybody to understand.

> no extra Python code,

I thought it should be better to use python rather than batch or PowerShell? Anyway, this shouldn't create problems, I believe.

> a whole automation of packaging,

As you can see it is automated. Both the [pango-build](https://github.com/naveen521kk/pango-build)(which I will any maintain for another project) and Github Actions here automatically builds things. It builds and also runs a simple command as a test see the GitHub workflow I added in this PR.

> packaging tests for all supported platforms.

I think it makes sense to pack only for Windows because for Linux it is there, by default, or can easily be installed through the package manager. The same is for macOS, they have Brew.

**Comment by naveen521kk** [comment]
Is it possible to review this at least now?

**Pull request closed without merging**
