### PR TITLE
Show how to include any header/footer on a PDF

### PR DESCRIPTION
**Pull request by nathandem**
This is the PR I mentioned in #92 

I tried to make it complete. I'm open to any suggestion for the merge, typo or else :)

### CODE REVIEW

**Comment by liZe** [comment]
Hello!

Thanks a lot. I should have merged this a long time ago, but… better late than never!

I don't know if a wiki page is better than a page in the documentation, but we can change this later.

**Comment by nathandem** [comment]
Didn't notice you merged it, cool :) Happy to have helped a bit!

**Comment by bjornasm** [comment]
Is this related to choosing your own header (instead of being the h2 heading of that section like it is on reports?) Cant find out how it is done.

**Comment by Tontyna** [comment]
@bjornasm see https://github.com/Kozea/WeasyPrint/issues/1140#issuecomment-643735794

**Pull request merged**
