### PR TITLE
Add support for VW and VH units

### PR DESCRIPTION
**Pull request by mousetail**
Add support for VW and VH units in certain contexts (basically anywhere percentages work except tables).

### CODE REVIEW

**Comment by liZe** [comment]
Hello!

Thanks a lot for this pull request.

Could it be possible to remove all the cosmetic changes probably introduced by your IDE (or a linter)? It adds a lot of noise and makes the PR really hard to read and to review.

Thank you!

**Comment by liZe** [comment]
> Could it be possible to remove all the cosmetic changes probably introduced by your IDE (or a linter)?

Thank you for your commit, but there are lots of lines with only formatting changes in the PR, even with your fix. I’m really sorry, but I’d really prefer a clean PR. Having these 17 modified files is hard to read, it would be really easier for me without the noise.

**Comment by pbregener** [comment]
This would be a great feature to have, but I agree that this PR is pretty hard to review due to lots of unrelated changes.
Would love to see this feature in the next release! Ping me if I can help to get this merged.

**Comment by mousetail** [comment]
FYI you can check the "hide white space changes" when reviewing. I made this pull request as part of a job where I no longer work.
I removed most formatting changes already though only ones far from significant changes because I didn't want to risk breaking things. This code will also require more better tests, I tested purely on one example but there are a lot of places where `vh` and `vw` can be used and I'm not sure if I covered all of them.

**Comment by liZe** [comment]
> FYI you can check the "hide white space changes" when reviewing.

The problem is not only the diff. Changing many lines for style in unrelated commits gives hard times when dealing with history.

> I made this pull request as part of a job where I no longer work.
> 
> I removed most formatting changes already though only ones far from significant changes because I didn't want to risk breaking things. This code will also require more better tests, I tested purely on one example but there are a lot of places where `vh` and `vw` can be used and I'm not sure if I covered all of them.

OK, thank you. I’ll find a solution to merge the changes if they’re OK.

**Pull request closed without merging**
