### PR TITLE
Named strings and counter names are case sensitive

### LINKED ISSUE #826: Uppercase characters in named strings dont work
Named strings seem to break when they contain uppercase characters in their label. See code snippet below. I would expect 'brokenTitle' to work as 'workingtitle'.

```<!doctype html>
<html>
<head>
    <style>
    div.page {
        page-break-after:always;
    }
    h1 {
      string-set: workingtitle content();
    }
    h2 {
      string-set: brokenTitle content();
    }
    #p1 {
        page: page1;
    }
    #p2 {
        page: paGe2;
    }
    @page {
        @top-left {
            content: string(workingtitle);
        }
        @top-right {
            content: string(brokenTitle);
        }
    }
    </style>
</head>
<body>
    <div class="page" id="p1">
      <h1>H1 Title on Page 1</h1>
      <h2>H2 Title on Page 1</h2>
    </div>
    <div class="page" id="p2">
      <h1>H1 Title on Page 1</h1>
      <h2>H2 Title on Page 2</h2>
    </div>
  </body>
</html>```

### PR DESCRIPTION
**Pull request by Tontyna**
Should close #826 

BTW: The case-sensitivity of counter names is buggy, too.

### CODE REVIEW

**Comment by liZe** [comment]
Thank you.

> BTW: The case-sensitivity of counter names is buggy, too.

I'll check that.

**Comment by Tontyna** [comment]
Addendum: The case-sensitivity of counter names ~~is~~ *was* buggy, too.
Should be fixed by the 2nd and 3rd commit of this PR

**Comment by Tontyna** [comment]
BTW: Was tempted ro add a boolean parameter `case_sensitive` to `get_keyword()` in `css.utils` to retrieve either `token.lower_value` or `token.value`

**Comment by liZe** [comment]
> BTW: Was tempted ro add a boolean parameter `case_sensitive` to `get_keyword()` in `css.utils` to retrieve either `token.lower_value` or `token.value`

I've added a `get_custom_ident` function. It's cheap and much clearer, we can use it everywhere it's needed.

> Should be fixed by the 2nd and 3rd commit of this PR

It was, thank you!

**Pull request merged**
