### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by ellmetha**

### CODE REVIEW

**Comment by SimonSapin** [comment]
The images are not rendering for me at https://github.com/erudit/WeasyPrint/blob/improve-readme/README.rst . Any idea why?

**Comment by liZe** [comment]
`shields.io` returns random timeout errors. Cool!

**Comment by liZe** [comment]
`shields.io` seems to be fixed. @SimonSapin can we merge?

**Comment by SimonSapin** [comment]
Thanks @ellmetha!

**Pull request merged**
