### PR TITLE
Add PageMode and PageLayout to PDF catalog

### PR DESCRIPTION
**Pull request by pmjdebruijn**
See Table 28 (page 73-75) in
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf

Thanks to #1789 for the inspiration

### CODE REVIEW

**Comment by pmjdebruijn** [comment]
Scribus outputs

```
/PageLayout /TwoColumnRight
/PageMode /UseOutlines

```

I also noticed that least Atril (and therefore probably Evince) does not honor WeasyPrint's output...

**Comment by pmjdebruijn** [comment]
I just realized pydyf.String() caused the difference, so this should be good now.

**Comment by liZe** [comment]
Hi!

Thanks a lot for this pull request.

There are some problems with this kind of features, as explained in #1789:
- there’s nothing in CSS or HTML to set this property,
- nothing prevents users from doing this in a post-processor stop or a finisher function,
- adding this feature would lead to accept an endless list of PDF features that will be hard to document and maintain.

This is a real life problem :smile:. Even if you took time and effort to propose this pull request, there are some problems already:
- code style is broken in CI,
- the public API is too close to the PDF names (both for words and for style) and not close to the vocabulary actually used by PDF readers,
- some possible values listed in the specification are not listed in the PR,
- there’s no test,
- there’s no documentation…

It doesn’t mean at all that your pull request is bad, it just means that adding maintainable and solid code is really hard :smile:.

Giving a general solution, as proposed in #1789, is a great way to solve this problem: users can do more, and are less limited to WeasyPrint’s API. For example, there’s no way to add an `OpenAction` field with your PR. We can bet that some people would propose a crazy command-line option allowing plain PDF dictionaries to "solve" that!

So, as explained in #1789, we’ll continue to propose post-processing steps instead of adding many other features.

We really do appreciate your effort to propose pull requests, and we hope that we’ll merge more of them. There are many open issues for bugs and feature requests, let’s please focus on them!

**Comment by pmjdebruijn** [comment]
The problem is that setting very basic metadata shouldn't require a custom script.

If you give me some guidance how to translate the PDF names into something in Weasyprint, I could possibly rework the PR...

**Comment by liZe** [comment]
> The problem is that setting very basic metadata shouldn't require a custom script.

I can understand your frustration, and I don’t like to refuse pull requests. But we clearly explained in #1789 that we weren’t interested in this feature, and our arguments are still valid.

If that’s very basic metadata, then it should be specified by HTML or CSS, just as document title, page size, outlines, creation date, creator tool, language, etc. But it’s not. Users always tend to think that what they want is basic, and the problem is that handling millions of basic problems is not a basic problem 😄.

> If you give me some guidance how to translate the PDF names into something in Weasyprint, I could possibly rework the PR...

As explained above, the problem is not the quality of your pull request.

The problem is that we don’t want to maintain code that adds a feature that can already be done using a custom script. Otherwise, we’ll end up adding tons of options that’ll take endless time to create, maintain, review, fix, test… We prefer to focus our limited time on problems that can’t be solved otherwise, and there are many open issues for that.

And if you don’t want to write a custom script, you can always use Ghostscript to tweak your PDF metadata, using just the CLI. Ghostscript is a really good example of how a tool can propose thousands of options, and the problems it causes with documentation :smile:.

**Pull request closed without merging**
