### PR TITLE
Enable counter-increment and -reset in page context

### LINKED ISSUE #289: counter-increment in '@page'?
It seems that `counter-increment` does not work in `@page` currently (increase 1 for each page). It would be a nice feature to implement, can even work as a workaround for #93 at this point. Plus, it is useful to maintain multiple counters.

### PR DESCRIPTION
**Pull request by Tontyna**
This PR makes it possible to reset and increment the page-based `page` counter. Furthermore own page-based counters can be definded. 
The predefined `pages` counter is immutable and pretty useless when the `page` counter is manipulated.

Should fix  #289 and (partly) #93.

Concerning `counter-reset: page`:
It's fine for giving the document an initial page number -- in `@page:first` -- but to make e.g. chapters start with page n° 1 ~~you better utilize appropriate document-based counters combined with `string-set`~~ there is no easy & intuitive solution.
The only solution I found was inserting empty divs, styled with `page: resetpage; break-before:always;`

### CODE REVIEW

**Comment by Tontyna** [comment]
@liZe: Does the spec allow to reset or increment page-based counters in document-context?

**Comment by liZe** [comment]
> @liZe: Does the spec allow to reset or increment page-based counters in document-context?

One thing is sure: resetting a counter creates a new instance, so you can't reset the counter in the document.

About incrementing (and even accessing) the counter in the document, here is the first sentence of the [Page based counter chapter](https://drafts.csswg.org/css-page/#page-based-counters):

> Counters can be defined and controlled within an `@page` rule, and used as content in page-margin boxes.

It's not 100% clear, but I think that page-based counters can only be controlled (ie. incremented, reset) in `@page` rules, and only displayed in page-margin boxes.

**Comment by liZe** [comment]
> but to make e.g. chapters start with page n° 1 there is no easy & intuitive solution.

Using a counter different from `page` and displaying it with `string-set` should do the trick.

**Comment by Tontyna** [comment]
> Using a counter different from `page` and displaying it with string-set should do the trick.

No it doesnt. Because in the document-context we dont know when to properly increment this counter.
Only page-context knows when a new page is created.

**Comment by Tontyna** [comment]
> It's not 100% clear, but I think that page-based counters can only be controlled (ie. incremented, reset) in @page rules, and only displayed in page-margin boxes.

[draft](https://drafts.csswg.org/css-page-3/#margin-property-list) allows counter properties in margin context

**Comment by Tontyna** [comment]
> resetting a [page based] counter [in document context]  creates a new instance.

Only when we consider the involved document element being a descendant of its page :grimacing: 

Can it be that controlling page numbering (a useful, widespread, normal, necessary task) is so hard to achieve? Isn't token into account by the ~~spec~~ draft?!

**Comment by liZe** [comment]
> No it doesnt. Because in the document-context we dont know when to properly increment this counter.
> Only page-context knows when a new page is created. In the document we merely can force a page-break.

Of course, you're right.

> draft allows counter properties in margin context

Yes, but using `counter-reset` and `counter-increment` creates a new instance of counters.

> Only when we consider the involved document element being a descendant of its page

Not exactly. Only when we consider the involved document not being the same block as its page (and it's definitely not).

> Can it be that controlling page numbering (a useful, widespread, normal, necessary task) is so hard to achieve? Isn't token into account by the spec draft?!

Isn't that what you want?
```html
<html>
  <style>
    @page {
      @bottom-center {
        content: counter(page);
      }
    }
    @page chapter {
      counter-reset: page 1;
    }
    h2 {
      page: chapter;
    }
  </style>
  <body>
    <h1>Book title</h1>

    <h2>Chapter 1</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a venenatis metus. Sed sed libero lacinia, rutrum metus vel, vehicula sapien. Nulla semper lobortis lectus, in consectetur quam sollicitudin eget. Praesent eu mauris convallis, lacinia quam et, mattis nulla. Ut semper dolor ut pretium tempor. Praesent malesuada vel massa sed vestibulum. Etiam condimentum, quam at rutrum volutpat, mauris nisl cursus turpis, imperdiet venenatis massa velit nec ligula. Sed condimentum euismod nisl ut interdum. Donec nec lacus ac turpis efficitur pulvinar at et risus. Nulla imperdiet tincidunt lacus quis hendrerit. Nulla sed pretium augue. Proin eu ante augue.
    </p>
    <p>
      Nam efficitur odio ac nisl cursus, eget vestibulum urna congue. Morbi porta at lectus vel gravida. Maecenas rhoncus, nulla in elementum mattis, purus ex volutpat nulla, ut rutrum elit dui non neque. Donec sed pulvinar enim, vel consectetur enim. Aliquam aliquet dui urna, ac imperdiet felis laoreet ac. Aenean eleifend ligula nec ante finibus, nec facilisis erat imperdiet. In hac habitasse platea dictumst. Suspendisse in augue ultrices, iaculis elit non, commodo nisl. Nulla ut sodales lorem. Pellentesque est erat, lacinia ut velit id, accumsan aliquet ligula. Nunc eget nulla venenatis, interdum libero et, vehicula dui. Fusce venenatis odio tellus, id molestie purus porttitor nec. Nam in ipsum eu mauris hendrerit feugiat.
    </p>
    <p>
      Ut rhoncus eleifend nisl, nec aliquam ante mollis sed. Nunc rutrum ligula sed turpis egestas pretium. Nam fermentum molestie lobortis. Aenean ultrices erat et erat lacinia tincidunt. Integer blandit tempus ligula, ac tempor metus gravida et. Nam ac dapibus metus, et tincidunt velit. Donec vel mi quis mauris lobortis sagittis in id augue. Quisque aliquet augue nec sapien eleifend varius. Pellentesque ipsum metus, pulvinar sit amet eros ac, cursus mollis purus. Duis vulputate finibus augue, at faucibus neque tincidunt eu. Aliquam dictum dignissim odio eu varius. Pellentesque magna sapien, viverra et interdum vitae, lacinia at nibh. Praesent ac venenatis arcu. Vestibulum nec nunc a lectus auctor tempor ut a nisl.
    </p>
    <p>
      Mauris sit amet felis sodales, pharetra tellus eget, lacinia turpis. Praesent vel pretium ipsum, tincidunt pellentesque sem. Donec eu sapien sit amet urna lobortis rhoncus feugiat a arcu. Aenean lacinia lobortis erat, eget lobortis sapien. Vestibulum eleifend nibh eget nibh porta, a fringilla nibh vulputate. Vivamus fringilla nec mauris consectetur rhoncus. Duis porta maximus nibh, vitae fermentum purus venenatis ac. Praesent maximus hendrerit fermentum. In sed leo a nisi dictum efficitur mattis nec arcu. Suspendisse nec eros justo. Etiam risus diam, mattis in turpis eu, rhoncus vehicula eros. Cras cursus hendrerit mi et lacinia. Nulla sollicitudin risus et vestibulum sollicitudin.
    </p>
    <p>
      Nulla iaculis magna et volutpat malesuada. Nulla condimentum eros vitae urna euismod tincidunt. Ut vitae dapibus nisi. Suspendisse eleifend, diam blandit interdum iaculis, nisi enim pulvinar felis, nec fringilla leo turpis vitae felis. Duis malesuada odio quis ante cursus, id porta leo egestas. Phasellus a dolor quis tortor pharetra convallis. Aliquam suscipit purus nulla, et suscipit odio lacinia id. Praesent malesuada tempor arcu, vitae dapibus ligula placerat non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse non urna elit. Morbi accumsan enim vel neque maximus, ac imperdiet nunc sollicitudin. Curabitur a lacinia elit. Sed quis lobortis tellus. Sed ultricies, mi ac elementum blandit, urna sapien tristique urna, et suscipit quam libero id nibh.
    </p>

    <h2>Chapter 2</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a venenatis metus. Sed sed libero lacinia, rutrum metus vel, vehicula sapien. Nulla semper lobortis lectus, in consectetur quam sollicitudin eget. Praesent eu mauris convallis, lacinia quam et, mattis nulla. Ut semper dolor ut pretium tempor. Praesent malesuada vel massa sed vestibulum. Etiam condimentum, quam at rutrum volutpat, mauris nisl cursus turpis, imperdiet venenatis massa velit nec ligula. Sed condimentum euismod nisl ut interdum. Donec nec lacus ac turpis efficitur pulvinar at et risus. Nulla imperdiet tincidunt lacus quis hendrerit. Nulla sed pretium augue. Proin eu ante augue.
    </p>
    <p>
      Nam efficitur odio ac nisl cursus, eget vestibulum urna congue. Morbi porta at lectus vel gravida. Maecenas rhoncus, nulla in elementum mattis, purus ex volutpat nulla, ut rutrum elit dui non neque. Donec sed pulvinar enim, vel consectetur enim. Aliquam aliquet dui urna, ac imperdiet felis laoreet ac. Aenean eleifend ligula nec ante finibus, nec facilisis erat imperdiet. In hac habitasse platea dictumst. Suspendisse in augue ultrices, iaculis elit non, commodo nisl. Nulla ut sodales lorem. Pellentesque est erat, lacinia ut velit id, accumsan aliquet ligula. Nunc eget nulla venenatis, interdum libero et, vehicula dui. Fusce venenatis odio tellus, id molestie purus porttitor nec. Nam in ipsum eu mauris hendrerit feugiat.
    </p>
    <p>
      Ut rhoncus eleifend nisl, nec aliquam ante mollis sed. Nunc rutrum ligula sed turpis egestas pretium. Nam fermentum molestie lobortis. Aenean ultrices erat et erat lacinia tincidunt. Integer blandit tempus ligula, ac tempor metus gravida et. Nam ac dapibus metus, et tincidunt velit. Donec vel mi quis mauris lobortis sagittis in id augue. Quisque aliquet augue nec sapien eleifend varius. Pellentesque ipsum metus, pulvinar sit amet eros ac, cursus mollis purus. Duis vulputate finibus augue, at faucibus neque tincidunt eu. Aliquam dictum dignissim odio eu varius. Pellentesque magna sapien, viverra et interdum vitae, lacinia at nibh. Praesent ac venenatis arcu. Vestibulum nec nunc a lectus auctor tempor ut a nisl.
    </p>
    <p>
      Mauris sit amet felis sodales, pharetra tellus eget, lacinia turpis. Praesent vel pretium ipsum, tincidunt pellentesque sem. Donec eu sapien sit amet urna lobortis rhoncus feugiat a arcu. Aenean lacinia lobortis erat, eget lobortis sapien. Vestibulum eleifend nibh eget nibh porta, a fringilla nibh vulputate. Vivamus fringilla nec mauris consectetur rhoncus. Duis porta maximus nibh, vitae fermentum purus venenatis ac. Praesent maximus hendrerit fermentum. In sed leo a nisi dictum efficitur mattis nec arcu. Suspendisse nec eros justo. Etiam risus diam, mattis in turpis eu, rhoncus vehicula eros. Cras cursus hendrerit mi et lacinia. Nulla sollicitudin risus et vestibulum sollicitudin.
    </p>
    <p>
      Nulla iaculis magna et volutpat malesuada. Nulla condimentum eros vitae urna euismod tincidunt. Ut vitae dapibus nisi. Suspendisse eleifend, diam blandit interdum iaculis, nisi enim pulvinar felis, nec fringilla leo turpis vitae felis. Duis malesuada odio quis ante cursus, id porta leo egestas. Phasellus a dolor quis tortor pharetra convallis. Aliquam suscipit purus nulla, et suscipit odio lacinia id. Praesent malesuada tempor arcu, vitae dapibus ligula placerat non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse non urna elit. Morbi accumsan enim vel neque maximus, ac imperdiet nunc sollicitudin. Curabitur a lacinia elit. Sed quis lobortis tellus. Sed ultricies, mi ac elementum blandit, urna sapien tristique urna, et suscipit quam libero id nibh.
    </p>

    <h2>Chapter 3</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a venenatis metus. Sed sed libero lacinia, rutrum metus vel, vehicula sapien. Nulla semper lobortis lectus, in consectetur quam sollicitudin eget. Praesent eu mauris convallis, lacinia quam et, mattis nulla. Ut semper dolor ut pretium tempor. Praesent malesuada vel massa sed vestibulum. Etiam condimentum, quam at rutrum volutpat, mauris nisl cursus turpis, imperdiet venenatis massa velit nec ligula. Sed condimentum euismod nisl ut interdum. Donec nec lacus ac turpis efficitur pulvinar at et risus. Nulla imperdiet tincidunt lacus quis hendrerit. Nulla sed pretium augue. Proin eu ante augue.
    </p>
    <p>
      Nam efficitur odio ac nisl cursus, eget vestibulum urna congue. Morbi porta at lectus vel gravida. Maecenas rhoncus, nulla in elementum mattis, purus ex volutpat nulla, ut rutrum elit dui non neque. Donec sed pulvinar enim, vel consectetur enim. Aliquam aliquet dui urna, ac imperdiet felis laoreet ac. Aenean eleifend ligula nec ante finibus, nec facilisis erat imperdiet. In hac habitasse platea dictumst. Suspendisse in augue ultrices, iaculis elit non, commodo nisl. Nulla ut sodales lorem. Pellentesque est erat, lacinia ut velit id, accumsan aliquet ligula. Nunc eget nulla venenatis, interdum libero et, vehicula dui. Fusce venenatis odio tellus, id molestie purus porttitor nec. Nam in ipsum eu mauris hendrerit feugiat.
    </p>
    <p>
      Ut rhoncus eleifend nisl, nec aliquam ante mollis sed. Nunc rutrum ligula sed turpis egestas pretium. Nam fermentum molestie lobortis. Aenean ultrices erat et erat lacinia tincidunt. Integer blandit tempus ligula, ac tempor metus gravida et. Nam ac dapibus metus, et tincidunt velit. Donec vel mi quis mauris lobortis sagittis in id augue. Quisque aliquet augue nec sapien eleifend varius. Pellentesque ipsum metus, pulvinar sit amet eros ac, cursus mollis purus. Duis vulputate finibus augue, at faucibus neque tincidunt eu. Aliquam dictum dignissim odio eu varius. Pellentesque magna sapien, viverra et interdum vitae, lacinia at nibh. Praesent ac venenatis arcu. Vestibulum nec nunc a lectus auctor tempor ut a nisl.
    </p>
    <p>
      Mauris sit amet felis sodales, pharetra tellus eget, lacinia turpis. Praesent vel pretium ipsum, tincidunt pellentesque sem. Donec eu sapien sit amet urna lobortis rhoncus feugiat a arcu. Aenean lacinia lobortis erat, eget lobortis sapien. Vestibulum eleifend nibh eget nibh porta, a fringilla nibh vulputate. Vivamus fringilla nec mauris consectetur rhoncus. Duis porta maximus nibh, vitae fermentum purus venenatis ac. Praesent maximus hendrerit fermentum. In sed leo a nisi dictum efficitur mattis nec arcu. Suspendisse nec eros justo. Etiam risus diam, mattis in turpis eu, rhoncus vehicula eros. Cras cursus hendrerit mi et lacinia. Nulla sollicitudin risus et vestibulum sollicitudin.
    </p>
    <p>
      Nulla iaculis magna et volutpat malesuada. Nulla condimentum eros vitae urna euismod tincidunt. Ut vitae dapibus nisi. Suspendisse eleifend, diam blandit interdum iaculis, nisi enim pulvinar felis, nec fringilla leo turpis vitae felis. Duis malesuada odio quis ante cursus, id porta leo egestas. Phasellus a dolor quis tortor pharetra convallis. Aliquam suscipit purus nulla, et suscipit odio lacinia id. Praesent malesuada tempor arcu, vitae dapibus ligula placerat non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse non urna elit. Morbi accumsan enim vel neque maximus, ac imperdiet nunc sollicitudin. Curabitur a lacinia elit. Sed quis lobortis tellus. Sed ultricies, mi ac elementum blandit, urna sapien tristique urna, et suscipit quam libero id nibh.
    </p>
  </body>
</html>
```

**Comment by Tontyna** [comment]
OMG! You're right! It works!

My error when trying to achieve this was: I didnt apply the `page: chapter` to the `<h2>` solely, but to a `<div class="chapter">`, wrapping the whole chapter, its heading together with its paragraphs. And of course, every page was number 1...

**Comment by Tontyna** [comment]
Are you shure that in margin context
> using counter-reset and counter-increment creates a new instance of counters.

counter-reset definitely does. That's implemented in this PR. 
But counter-increment? I thought counter-increment creates a new counter only when that counter doesn't exist yet.

Probably youre right. I'll never grasp those nested counters and their scope.

BTW: I was surprised when I detected that as soon as there is a list in my document there is a counter named `list-item` present until the html ends. Naively had expected that counter to vanish at the list's closing tag.

**Comment by liZe** [comment]
> But counter-increment? I thought counter-increment creates a new counter only when that counter doesn't exist yet.

`counter-increment` doesn't create a new instance in a document, but it does in a page margin: "If a counter is reset or incremented within a margin context, it is in scope for that page-margin box and obscures any counters of the same name in both the page context and the document."

**Comment by Tontyna** [comment]
I dont' get it without an example.

```css
@page {
  counter-increment: pagebased;
  @top-center {
    counter-reset: page 1 pagebased 1 topbased 1;
    content: "top-center:: page: " counters(page, '.') " pagebased: " counters(pagebased, '.') " topbased: " counters(topbased, '.')
  }
  @bottom-center {
    counter-increment: page pagebased topbased;
    content: "bottom-center:: page: " counters(page, '.') " pagebased: " counters(pagebased, '.') " topbased: " counters(topbased, '.')
  }
}
```

Currently this PR produces (on the first page):

  - top-center:: page: 1.1 pagebased: 1.1 topbased: 1
  - bottom-center:: page: 2 pagebased: 2 topbased: 1
  
The bottom-center looked right until your explanation made me doubt. If a "new instance" is created there should be two numbers for page and pagebased...

**Comment by liZe** [comment]
> The bottom-center looked right until your explanation made me doubt. If a "new instance" is created there should be two numbers for page and pagebased...

As far as I understand the spec, the content of @bottom-center should be page: 1.1 pagebased: 1.1 topbased: 1.

But… Who cares :wink:?

**Comment by Tontyna** [comment]
So let's decide for the *no new instance* version.
Feels organic, `formatting_structures.build.update_counters()` works out of the box.

BTW: That's what everybody expects until reading the spec distracts his brain. See [your comment](https://github.com/Kozea/WeasyPrint/issues/289#issuecomment-389860402)

**Comment by liZe** [comment]
> BTW: That's what everybody expects until reading the spec distracts his brain. See your comment

Good catch! We should get in touch with the W3C.

Can I merge?

**Comment by Tontyna** [comment]
> Can I merge?

Yes.

**Pull request merged**
