### PR TITLE
Add support for use when frozen

### PR DESCRIPTION
**Pull request by andrewleech**
Use appropriate path to find resource when frozen (using py2exe etc.)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’m not familiar with py2exe, but this looks reasonable.

The Travis-CI build fails with flake8 errors:

```
weasyprint/html.py:37:80: E501 line too long (95 > 79 characters)
weasyprint/html.py:38:36: E251 unexpected spaces around keyword / parameter equals
```

(You can use `pip install flake8` to run it locally.) Please fix that, and this should be good to go.

**Comment by andrewleech** [comment]
Hi,
I've fixed the formatting to satisfy flake8. 
There's another issue with the pypy build, have you seen it before? 
If not it's probably related to my change somehow.

**Comment by SimonSapin** [comment]
Yeah, this is probably https://bitbucket.org/pypy/pypy/issues/1357/lxml-not-returning-the-same-proxy-object , though it’s the first time I see it happen in the test suite.

Looks good, thanks!

**Comment by andrewleech** [comment]
Great thanks!

**Pull request merged**
